Add: check workflow status

diff --git a/.github/workflows/dependabot-automerge.yml b/.github/workflows/dependabot-automerge.yml
--- a/.github/workflows/dependabot-automerge.yml
+++ b/.github/workflows/dependabot-automerge.yml
@@ -22,7 +22,18 @@ jobs:
         uses: dependabot/fetch-metadata@v2
         with:
           github-token: "${{ secrets.GITHUB_TOKEN }}"
-      
+        
+      - name: Check workflow status
+        id: check_workflows
+        run: |
+          failed_runs=$(gh run list --workflow="Build" --branch="${{ github.head_ref }}" --json conclusion --jq '.[] | select(.conclusion != "success" and .conclusion != null) | .conclusion')
+          if [ -n "$failed_runs" ]; then
+            echo "Some workflow runs failed or are still in progress"
+            exit 1
+          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        
       - name: Approve pull request
         run: gh pr review --approve "$PR_URL"
         env:
@@ -31,6 +42,10 @@ jobs:
       
       - name: Enable auto-merge for Dependabot PRs
         run: |
+          # 1. The update type must be a minor or patch update which ensures we are merging less disruptive changes.
+          # 2. The dependency type must be either direct or direct-development which ensures that we only auto-merge 
+          #    changes that are directly related to the project.
+          
           UPDATE_TYPE="${{ steps.metadata.outputs.update-type }}"
           DEPENDENCY_TYPE="${{ steps.metadata.outputs.dependency-type }}"
           
